# Generated by Django 3.2.7 on 2021-11-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_liability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liability',
        ),
    ]
