# Generated by Django 3.2.7 on 2021-12-20 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_delete_liability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(blank=True, max_length=64, null=True)),
                ('ticker', models.CharField(blank=True, max_length=16, null=True)),
                ('full_name', models.CharField(blank=True, max_length=64, null=True)),
                ('sector', models.CharField(blank=True, max_length=64, null=True)),
                ('industry', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='securities',
            field=models.ManyToManyField(to='finance.Security'),
        ),
    ]
