# Generated by Django 3.2.7 on 2022-01-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20211220_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'Securities'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='securities',
        ),
        migrations.AddField(
            model_name='account',
            name='type_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.institution'),
        ),
    ]
