const blueMoveDict = {
    '0':{'name':"NULL",'type':'TYPELESS','PP':0,'basepower':0,'accuracy':0,'description':'NULL'},
    '1':{'name':"POUND",'type':'NORMAL','PP':35,'basepower':40,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '2':{'name':"KARATE CHOP",'type':'FIGHTING','PP':25,'basepower':50,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '3':{'name':"DOUBLESLAP",'type':'NORMAL','PP':10,'basepower':15,'accuracy':90,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '4':{'name':"COMET PUNCH",'type':'FIGHTING','PP':15,'basepower':25,'accuracy':90,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '5':{'name':"MEGA PUNCH",'type':'NORMAL','PP':20,'basepower':80,'accuracy':85,'description':'NO_ADDITIONAL_EFFECT'},
    '6':{'name':"PAY DAY",'type':'NORMAL','PP':20,'basepower':40,'accuracy':100,'description':'PAY_DAY_EFFECT'},
    '7':{'name':"FIRE PUNCH",'type':'FIRE','PP':15,'basepower':75,'accuracy':100,'description':'BURN_SIDE_EFFECT1'},
    '8':{'name':"ICE PUNCH",'type':'ICE','PP':15,'basepower':75,'accuracy':100,'description':'FREEZE_SIDE_EFFECT'},
    '9':{'name':"THUNDERPUNCH",'type':'ELECTRIC','PP':15,'basepower':75,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT1'},
    '10':{'name':"SCRATCH",'type':'NORMAL','PP':35,'basepower':40,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '11':{'name':"VICEGRIP",'type':'NORMAL','PP':30,'basepower':55,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '12':{'name':"GUILLOTINE",'type':'BUG','PP':5,'basepower':1,'accuracy':50,'description':'OHKO_EFFECT'},
    '13':{'name':"RAZOR WIND",'type':'FLYING','PP':10,'basepower':80,'accuracy':100,'description':'CHARGE_EFFECT'},
    '14':{'name':"SWORDS DANCE",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'ATTACK_UP2_EFFECT'},
    '15':{'name':"CUT",'type':'BUG','PP':30,'basepower':60,'accuracy':95,'description':'NO_ADDITIONAL_EFFECT'},
    '16':{'name':"GUST",'type':'FLYING','PP':35,'basepower':40,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '17':{'name':"WING ATTACK",'type':'FLYING','PP':35,'basepower':70,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '18':{'name':"WHIRLWIND",'type':'FLYING','PP':20,'basepower':0,'accuracy':100,'description':'SWITCH_AND_TELEPORT_EFFECT'},
    '19':{'name':"FLY",'type':'FLYING','PP':15,'basepower':65,'accuracy':95,'description':'FLY_EFFECT'},
    '20':{'name':"BIND",'type':'NORMAL','PP':20,'basepower':15,'accuracy':85,'description':'TRAPPING_EFFECT'},
    '21':{'name':"SLAM",'type':'NORMAL','PP':20,'basepower':80,'accuracy':85,'description':'NO_ADDITIONAL_EFFECT'},
    '22':{'name':"VINE WHIP",'type':'GRASS','PP':20,'basepower':60,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '23':{'name':"STOMP",'type':'NORMAL','PP':20,'basepower':65,'accuracy':100,'description':'FLINCH_SIDE_EFFECT2'},
    '24':{'name':"DOUBLE KICK",'type':'FIGHTING','PP':30,'basepower':30,'accuracy':100,'description':'ATTACK_TWICE_EFFECT'},
    '25':{'name':"MEGA KICK",'type':'NORMAL','PP':5,'basepower':120,'accuracy':75,'description':'NO_ADDITIONAL_EFFECT'},
    '26':{'name':"JUMP KICK",'type':'FIGHTING','PP':25,'basepower':70,'accuracy':95,'description':'JUMP_KICK_EFFECT'},
    '27':{'name':"ROLLING KICK",'type':'FIGHTING','PP':15,'basepower':60,'accuracy':85,'description':'FLINCH_SIDE_EFFECT2'},
    '28':{'name':"SAND-ATTACK",'type':'GROUND','PP':15,'basepower':0,'accuracy':100,'description':'ACCURACY_DOWN1_EFFECT'},
    '29':{'name':"HEADBUTT",'type':'NORMAL','PP':15,'basepower':70,'accuracy':100,'description':'FLINCH_SIDE_EFFECT2'},
    '30':{'name':"HORN ATTACK",'type':'NORMAL','PP':25,'basepower':65,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '31':{'name':"FURY ATTACK",'type':'NORMAL','PP':20,'basepower':15,'accuracy':100,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '32':{'name':"HORN DRILL",'type':'NORMAL','PP':5,'basepower':1,'accuracy':50,'description':'OHKO_EFFECT'},
    '33':{'name':"TACKLE",'type':'NORMAL','PP':35,'basepower':35,'accuracy':95,'description':'NO_ADDITIONAL_EFFECT'},
    '34':{'name':"BODY SLAM",'type':'NORMAL','PP':15,'basepower':85,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT2'},
    '35':{'name':"WRAP",'type':'NORMAL','PP':20,'basepower':15,'accuracy':85,'description':'TRAPPING_EFFECT'},
    '36':{'name':"TAKE DOWN",'type':'NORMAL','PP':20,'basepower':90,'accuracy':85,'description':'RECOIL_EFFECT'},
    '37':{'name':"THRASH",'type':'NORMAL','PP':20,'basepower':90,'accuracy':100,'description':'THRASH_PETAL_DANCE_EFFECT'},
    '38':{'name':"DOUBLE-EDGE",'type':'NORMAL','PP':15,'basepower':100,'accuracy':100,'description':'RECOIL_EFFECT'},
    '39':{'name':"TAIL WHIP",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'DEFENSE_DOWN1_EFFECT'},
    '40':{'name':"POISON STING",'type':'POISON','PP':35,'basepower':15,'accuracy':100,'description':'POISON_SIDE_EFFECT1'},
    '41':{'name':"TWINEEDLE",'type':'BUG','PP':20,'basepower':40,'accuracy':100,'description':'TWINEEDLE_EFFECT'},
    '42':{'name':"PIN MISSILE",'type':'BUG','PP':20,'basepower':25,'accuracy':85,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '43':{'name':"LEER",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'DEFENSE_DOWN1_EFFECT'},
    '44':{'name':"BITE",'type':'NORMAL','PP':25,'basepower':60,'accuracy':100,'description':'FLINCH_SIDE_EFFECT1'},
    '45':{'name':"GROWL",'type':'NORMAL','PP':40,'basepower':0,'accuracy':100,'description':'ATTACK_DOWN1_EFFECT'},
    '46':{'name':"ROAR",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'SWITCH_AND_TELEPORT_EFFECT'},
    '47':{'name':"SING",'type':'NORMAL','PP':15,'basepower':0,'accuracy':70,'description':'SLEEP_EFFECT'},
    '48':{'name':"SUPERSONIC",'type':'NORMAL','PP':20,'basepower':0,'accuracy':70,'description':'CONFUSION_EFFECT'},
    '49':{'name':"SONICBOOM",'type':'NORMAL','PP':20,'basepower':40,'accuracy':90,'description':'SPECIAL_DAMAGE_EFFECT'},
    '50':{'name':"DISABLE",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'DISABLE_EFFECT'},
    '51':{'name':"ACID",'type':'POISON','PP':30,'basepower':40,'accuracy':100,'description':'DEFENSE_DOWN_SIDE_EFFECT'},
    '52':{'name':"EMBER",'type':'FIRE','PP':25,'basepower':40,'accuracy':100,'description':'BURN_SIDE_EFFECT1'},
    '53':{'name':"FLAMETHROWER",'type':'FIRE','PP':15,'basepower':95,'accuracy':100,'description':'BURN_SIDE_EFFECT1'},
    '54':{'name':"MIST",'type':'ICE','PP':30,'basepower':0,'accuracy':100,'description':'MIST_EFFECT'},
    '55':{'name':"WATER GUN",'type':'WATER','PP':20,'basepower':60,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '56':{'name':"HYDRO PUMP",'type':'WATER','PP':10,'basepower':100,'accuracy':90,'description':'NO_ADDITIONAL_EFFECT'},
    '57':{'name':"SURF",'type':'WATER','PP':15,'basepower':95,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '58':{'name':"ICE BEAM",'type':'ICE','PP':10,'basepower':95,'accuracy':100,'description':'FREEZE_SIDE_EFFECT'},
    '59':{'name':"BLIZZARD",'type':'ICE','PP':5,'basepower':120,'accuracy':90,'description':'FREEZE_SIDE_EFFECT'},
    '60':{'name':"PSYBEAM",'type':'PSYCHIC_TYPE','PP':20,'basepower':65,'accuracy':100,'description':'CONFUSION_SIDE_EFFECT'},
    '61':{'name':"BUBBLEBEAM",'type':'WATER','PP':20,'basepower':65,'accuracy':100,'description':'SPEED_DOWN_SIDE_EFFECT'},
    '62':{'name':"AURORA BEAM",'type':'ICE','PP':20,'basepower':65,'accuracy':100,'description':'ATTACK_DOWN_SIDE_EFFECT'},
    '63':{'name':"HYPER BEAM",'type':'NORMAL','PP':5,'basepower':150,'accuracy':90,'description':'HYPER_BEAM_EFFECT'},
    '64':{'name':"PECK",'type':'FLYING','PP':35,'basepower':35,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '65':{'name':"DRILL PECK",'type':'FLYING','PP':20,'basepower':80,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '66':{'name':"SUBMISSION",'type':'FIGHTING','PP':25,'basepower':80,'accuracy':100,'description':'RECOIL_EFFECT'},
    '67':{'name':"LOW KICK",'type':'FIGHTING','PP':20,'basepower':50,'accuracy':90,'description':'FLINCH_SIDE_EFFECT2'},
    '68':{'name':"COUNTER",'type':'FIGHTING','PP':20,'basepower':1,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '69':{'name':"SEISMIC TOSS",'type':'FIGHTING','PP':20,'basepower':0,'accuracy':100,'description':'SPECIAL_DAMAGE_EFFECT'},
    '70':{'name':"STRENGTH",'type':'NORMAL','PP':15,'basepower':80,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '71':{'name':"ABSORB",'type':'GRASS','PP':20,'basepower':40,'accuracy':100,'description':'DRAIN_HP_EFFECT'},
    '72':{'name':"MEGA DRAIN",'type':'GRASS','PP':10,'basepower':80,'accuracy':100,'description':'DRAIN_HP_EFFECT'},
    '73':{'name':"LEECH SEED",'type':'GRASS','PP':10,'basepower':0,'accuracy':90,'description':'LEECH_SEED_EFFECT'},
    '74':{'name':"GROWTH",'type':'NORMAL','PP':40,'basepower':0,'accuracy':100,'description':'SPECIAL_UP1_EFFECT'},
    '75':{'name':"RAZOR LEAF",'type':'GRASS','PP':25,'basepower':55,'accuracy':95,'description':'NO_ADDITIONAL_EFFECT'},
    '76':{'name':"SOLARBEAM",'type':'GRASS','PP':10,'basepower':120,'accuracy':100,'description':'CHARGE_EFFECT'},
    '77':{'name':"POISONPOWDER",'type':'POISON','PP':35,'basepower':0,'accuracy':75,'description':'POISON_EFFECT'},
    '78':{'name':"STUN SPORE",'type':'GRASS','PP':30,'basepower':0,'accuracy':75,'description':'PARALYZE_EFFECT'},
    '79':{'name':"SLEEP POWDER",'type':'GRASS','PP':15,'basepower':0,'accuracy':75,'description':'SLEEP_EFFECT'},
    '80':{'name':"PETAL DANCE",'type':'GRASS','PP':20,'basepower':85,'accuracy':100,'description':'THRASH_PETAL_DANCE_EFFECT'},
    '81':{'name':"STRING SHOT",'type':'BUG','PP':40,'basepower':0,'accuracy':95,'description':'SPEED_DOWN1_EFFECT'},
    '82':{'name':"DRAGON RAGE",'type':'DRAGON','PP':10,'basepower':70,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '83':{'name':"FIRE SPIN",'type':'FIRE','PP':15,'basepower':15,'accuracy':85,'description':'TRAPPING_EFFECT'},
    '84':{'name':"THUNDERSHOCK",'type':'ELECTRIC','PP':30,'basepower':40,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT1'},
    '85':{'name':"THUNDERBOLT",'type':'ELECTRIC','PP':15,'basepower':95,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT1'},
    '86':{'name':"THUNDER WAVE",'type':'ELECTRIC','PP':20,'basepower':0,'accuracy':100,'description':'PARALYZE_EFFECT'},
    '87':{'name':"THUNDER",'type':'ELECTRIC','PP':10,'basepower':120,'accuracy':70,'description':'PARALYZE_SIDE_EFFECT1'},
    '88':{'name':"ROCK THROW",'type':'ROCK','PP':15,'basepower':50,'accuracy':80,'description':'NO_ADDITIONAL_EFFECT'},
    '89':{'name':"EARTHQUAKE",'type':'GROUND','PP':10,'basepower':100,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '90':{'name':"FISSURE",'type':'GROUND','PP':5,'basepower':1,'accuracy':50,'description':'OHKO_EFFECT'},
    '91':{'name':"DIG",'type':'GROUND','PP':10,'basepower':60,'accuracy':100,'description':'CHARGE_EFFECT'},
    '92':{'name':"TOXIC",'type':'POISON','PP':10,'basepower':0,'accuracy':85,'description':'POISON_EFFECT'},
    '93':{'name':"CONFUSION",'type':'PSYCHIC_TYPE','PP':25,'basepower':50,'accuracy':100,'description':'CONFUSION_SIDE_EFFECT'},
    '94':{'name':"PSYCHIC",'type':'PSYCHIC_TYPE','PP':10,'basepower':90,'accuracy':100,'description':'SPECIAL_DOWN_SIDE_EFFECT'},
    '95':{'name':"HYPNOSIS",'type':'PSYCHIC_TYPE','PP':20,'basepower':0,'accuracy':60,'description':'SLEEP_EFFECT'},
    '96':{'name':"MEDITATE",'type':'PSYCHIC_TYPE','PP':40,'basepower':0,'accuracy':100,'description':'ATTACK_SPECIAL_SPEED_UP1'},
    '97':{'name':"AGILITY",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'SPEED_UP2_EFFECT'},
    '98':{'name':"QUICK ATTACK",'type':'NORMAL','PP':30,'basepower':40,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '99':{'name':"RAGE",'type':'NORMAL','PP':20,'basepower':40,'accuracy':100,'description':'RAGE_EFFECT'},
    '100':{'name':"TELEPORT",'type':'PSYCHIC_TYPE','PP':20,'basepower':0,'accuracy':100,'description':'SWITCH_AND_TELEPORT_EFFECT'},
    '101':{'name':"NIGHT SHADE",'type':'GHOST','PP':15,'basepower':0,'accuracy':100,'description':'SPECIAL_DAMAGE_EFFECT'},
    '102':{'name':"MIMIC",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'MIMIC_EFFECT'},
    '103':{'name':"SCREECH",'type':'NORMAL','PP':40,'basepower':0,'accuracy':85,'description':'DEFENSE_DOWN2_EFFECT'},
    '104':{'name':"DOUBLE TEAM",'type':'NORMAL','PP':15,'basepower':0,'accuracy':100,'description':'EVASION_UP1_EFFECT'},
    '105':{'name':"RECOVER",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'HEAL_EFFECT'},
    '106':{'name':"HARDEN",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'DEFENSE_UP1_EFFECT'},
    '107':{'name':"MINIMIZE",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'EVASION_UP1_EFFECT'},
    '108':{'name':"SMOKESCREEN",'type':'POISON','PP':20,'basepower':0,'accuracy':100,'description':'ACCURACY_DOWN1_EFFECT'},
    '109':{'name':"CONFUSE RAY",'type':'GHOST','PP':10,'basepower':0,'accuracy':100,'description':'CONFUSION_EFFECT'},
    '110':{'name':"WITHDRAW",'type':'WATER','PP':20,'basepower':0,'accuracy':100,'description':'HEAL_EFFECT'},
    '111':{'name':"DEFENSE CURL",'type':'NORMAL','PP':40,'basepower':0,'accuracy':100,'description':'DEFENSE_UP1_EFFECT'},
    '112':{'name':"BARRIER",'type':'PSYCHIC_TYPE','PP':30,'basepower':0,'accuracy':100,'description':'DEFENSE_UP2_EFFECT'},
    '113':{'name':"LIGHT SCREEN",'type':'PSYCHIC_TYPE','PP':30,'basepower':0,'accuracy':100,'description':'LIGHT_SCREEN_EFFECT'},
    '114':{'name':"HAZE",'type':'POISON','PP':30,'basepower':0,'accuracy':100,'description':'HAZE_EFFECT'},
    '115':{'name':"REFLECT",'type':'PSYCHIC_TYPE','PP':20,'basepower':0,'accuracy':100,'description':'REFLECT_EFFECT'},
    '116':{'name':"SHADOWBALL",'type':'GHOST','PP':20,'basepower':80,'accuracy':100,'description':'DEFENSE_DOWN_SIDE_EFFECT'},
    '117':{'name':"ROLL TACKLE",'type':'ROCK','PP':15,'basepower':65,'accuracy':100,'description':'ATTACK_UP_SIDE_EFFECT'},
    '118':{'name':"METRONOME",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'METRONOME_EFFECT'},
    '119':{'name':"MIRROR MOVE",'type':'FLYING','PP':20,'basepower':0,'accuracy':100,'description':'MIRROR_MOVE_EFFECT'},
    '120':{'name':"SELFDESTRUCT",'type':'NORMAL','PP':5,'basepower':130,'accuracy':100,'description':'EXPLODE_EFFECT'},
    '121':{'name':"EGG BOMB",'type':'NORMAL','PP':10,'basepower':100,'accuracy':75,'description':'CONFUSION_SIDE_EFFECT'},
    '122':{'name':"LICK",'type':'GHOST','PP':30,'basepower':50,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT2'},
    '123':{'name':"SMOG",'type':'POISON','PP':20,'basepower':40,'accuracy':90,'description':'POISON_SIDE_EFFECT2'},
    '124':{'name':"SLUDGE",'type':'POISON','PP':20,'basepower':65,'accuracy':100,'description':'POISON_SIDE_EFFECT2'},
    '125':{'name':"BONE CLUB",'type':'GROUND','PP':20,'basepower':65,'accuracy':85,'description':'FLINCH_SIDE_EFFECT1'},
    '126':{'name':"FIRE BLAST",'type':'FIRE','PP':5,'basepower':120,'accuracy':85,'description':'BURN_SIDE_EFFECT2'},
    '127':{'name':"WATERFALL",'type':'WATER','PP':15,'basepower':80,'accuracy':100,'description':'FLINCH_SIDE_EFFECT1'},
    '128':{'name':"CLAMP",'type':'WATER','PP':10,'basepower':35,'accuracy':90,'description':'TRAPPING_EFFECT'},
    '129':{'name':"SWIFT",'type':'NORMAL','PP':20,'basepower':65,'accuracy':100,'description':'SWIFT_EFFECT'},
    '130':{'name':"SKULL BASH",'type':'NORMAL','PP':15,'basepower':100,'accuracy':100,'description':'RECOIL_EFFECT'},
    '131':{'name':"SPIKE CANNON",'type':'NORMAL','PP':15,'basepower':20,'accuracy':100,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '132':{'name':"CONSTRICT",'type':'NORMAL','PP':35,'basepower':40,'accuracy':100,'description':'SPEED_DOWN_SIDE_EFFECT'},
    '133':{'name':"AMNESIA",'type':'PSYCHIC_TYPE','PP':20,'basepower':0,'accuracy':100,'description':'SPECIAL_UP2_EFFECT'},
    '134':{'name':"KINESIS",'type':'PSYCHIC_TYPE','PP':15,'basepower':0,'accuracy':100,'description':'ACCURACY_DOWN1_EFFECT'},
    '135':{'name':"SOFTBOILED",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'HEAL_EFFECT'},
    '136':{'name':"HI JUMP KICK",'type':'FIGHTING','PP':20,'basepower':85,'accuracy':90,'description':'JUMP_KICK_EFFECT'},
    '137':{'name':"GLARE",'type':'NORMAL','PP':30,'basepower':0,'accuracy':90,'description':'PARALYZE_EFFECT'},
    '138':{'name':"DREAM EATER",'type':'GHOST','PP':15,'basepower':100,'accuracy':100,'description':'DREAM_EATER_EFFECT'},
    '139':{'name':"POISON GAS",'type':'POISON','PP':40,'basepower':0,'accuracy':100,'description':'POISON_EFFECT'},
    '140':{'name':"BARRAGE",'type':'GRASS','PP':20,'basepower':15,'accuracy':100,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '141':{'name':"LEECH LIFE",'type':'BUG','PP':15,'basepower':50,'accuracy':100,'description':'DRAIN_HP_EFFECT'},
    '142':{'name':"LOVELY KISS",'type':'NORMAL','PP':10,'basepower':0,'accuracy':80,'description':'SLEEP_EFFECT'},
    '143':{'name':"SKY ATTACK",'type':'FLYING','PP':5,'basepower':140,'accuracy':90,'description':'HYPER_BEAM_EFFECT'},
    '144':{'name':"TRANSFORM",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'TRANSFORM_EFFECT'},
    '145':{'name':"BUBBLE",'type':'WATER','PP':30,'basepower':20,'accuracy':100,'description':'SPEED_DOWN_SIDE_EFFECT'},
    '146':{'name':"DIZZY PUNCH",'type':'NORMAL','PP':10,'basepower':70,'accuracy':100,'description':'CONFUSION_SIDE_EFFECT'},
    '147':{'name':"SPORE",'type':'GRASS','PP':15,'basepower':0,'accuracy':100,'description':'SLEEP_EFFECT'},
    '148':{'name':"FLASH",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'ACCURACY_DOWN1_EFFECT'},
    '149':{'name':"PSYWAVE",'type':'PSYCHIC_TYPE','PP':15,'basepower':1,'accuracy':80,'description':'SPECIAL_DAMAGE_EFFECT'},
    '150':{'name':"SPLASH",'type':'NORMAL','PP':40,'basepower':0,'accuracy':100,'description':'SPLASH_EFFECT'},
    '151':{'name':"ACID ARMOR",'type':'POISON','PP':40,'basepower':0,'accuracy':100,'description':'DEFENSE_UP2_EFFECT'},
    '152':{'name':"CRABHAMMER",'type':'WATER','PP':10,'basepower':90,'accuracy':85,'description':'NO_ADDITIONAL_EFFECT'},
    '153':{'name':"EXPLOSION",'type':'NORMAL','PP':5,'basepower':170,'accuracy':100,'description':'EXPLODE_EFFECT'},
    '154':{'name':"FURY SWIPES",'type':'NORMAL','PP':15,'basepower':25,'accuracy':80,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '155':{'name':"BONEMERANG",'type':'GROUND','PP':10,'basepower':50,'accuracy':90,'description':'ATTACK_TWICE_EFFECT'},
    '156':{'name':"REST",'type':'PSYCHIC_TYPE','PP':10,'basepower':0,'accuracy':100,'description':'HEAL_EFFECT'},
    '157':{'name':"ROCK SLIDE",'type':'ROCK','PP':15,'basepower':75,'accuracy':90,'description':'FLINCH_SIDE_EFFECT1'},
    '158':{'name':"HYPER FANG",'type':'NORMAL','PP':15,'basepower':80,'accuracy':90,'description':'FLINCH_SIDE_EFFECT1'},
    '159':{'name':"SHARPEN",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'ATTACK_ACCURACY_UP1_EFFECT'},
    '160':{'name':"CONVERSION",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'CONVERSION_EFFECT'},
    '161':{'name':"TRI ATTACK",'type':'NORMAL','PP':10,'basepower':80,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '162':{'name':"SUPER FANG",'type':'NORMAL','PP':10,'basepower':1,'accuracy':90,'description':'SUPER_FANG_EFFECT'},
    '163':{'name':"SLASH",'type':'NORMAL','PP':20,'basepower':70,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '164':{'name':"SUBSTITUTE",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'SUBSTITUTE_EFFECT'},
    '165':{'name':"STRUGGLE",'type':'TYPELESS','PP':10,'basepower':50,'accuracy':100,'description':'RECOIL_EFFECT'}
};

const moveDict = {
    '0':{'name':"NULL",'type':'TYPELESS','PP':0,'basepower':0,'accuracy':0,'description':'NULL'},
    '1':{'name':"POUND",'type':'NORMAL','PP':35,'basepower':40,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '2':{'name':"KARATE CHOP",'type':'FIGHTING','PP':25,'basepower':50,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '3':{'name':"DOUBLESLAP",'type':'NORMAL','PP':10,'basepower':15,'accuracy':90,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '4':{'name':"COMET PUNCH",'type':'FIGHTING','PP':15,'basepower':25,'accuracy':90,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '5':{'name':"MEGA PUNCH",'type':'NORMAL','PP':20,'basepower':80,'accuracy':85,'description':'NO_ADDITIONAL_EFFECT'},
    '6':{'name':"PAY DAY",'type':'NORMAL','PP':20,'basepower':40,'accuracy':100,'description':'PAY_DAY_EFFECT'},
    '7':{'name':"FIRE PUNCH",'type':'FIRE','PP':15,'basepower':75,'accuracy':100,'description':'BURN_SIDE_EFFECT1'},
    '8':{'name':"ICE PUNCH",'type':'ICE','PP':15,'basepower':75,'accuracy':100,'description':'FREEZE_SIDE_EFFECT'},
    '9':{'name':"THUNDERPUNCH",'type':'ELECTRIC','PP':15,'basepower':75,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT1'},
    '10':{'name':"SCRATCH",'type':'NORMAL','PP':35,'basepower':40,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '11':{'name':"VICEGRIP",'type':'NORMAL','PP':30,'basepower':55,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '12':{'name':"GUILLOTINE",'type':'BUG','PP':5,'basepower':1,'accuracy':50,'description':'OHKO_EFFECT'},
    '13':{'name':"RAZOR WIND",'type':'FLYING','PP':10,'basepower':80,'accuracy':100,'description':'CHARGE_EFFECT'},
    '14':{'name':"SWORDS DANCE",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'ATTACK_UP2_EFFECT'},
    '15':{'name':"CUT",'type':'BUG','PP':30,'basepower':60,'accuracy':95,'description':'NO_ADDITIONAL_EFFECT'},
    '16':{'name':"GUST",'type':'FLYING','PP':35,'basepower':40,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '17':{'name':"WING ATTACK",'type':'FLYING','PP':35,'basepower':70,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '18':{'name':"WHIRLWIND",'type':'FLYING','PP':20,'basepower':0,'accuracy':100,'description':'SWITCH_AND_TELEPORT_EFFECT'},
    '19':{'name':"FLY",'type':'FLYING','PP':15,'basepower':65,'accuracy':95,'description':'FLY_EFFECT'},
    '20':{'name':"BIND",'type':'NORMAL','PP':20,'basepower':15,'accuracy':85,'description':'TRAPPING_EFFECT'},
    '21':{'name':"SLAM",'type':'NORMAL','PP':20,'basepower':80,'accuracy':85,'description':'NO_ADDITIONAL_EFFECT'},
    '22':{'name':"VINE WHIP",'type':'GRASS','PP':20,'basepower':60,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '23':{'name':"STOMP",'type':'NORMAL','PP':20,'basepower':65,'accuracy':100,'description':'FLINCH_SIDE_EFFECT2'},
    '24':{'name':"DOUBLE KICK",'type':'FIGHTING','PP':30,'basepower':30,'accuracy':100,'description':'ATTACK_TWICE_EFFECT'},
    '25':{'name':"MEGA KICK",'type':'NORMAL','PP':5,'basepower':120,'accuracy':75,'description':'NO_ADDITIONAL_EFFECT'},
    '26':{'name':"JUMP KICK",'type':'FIGHTING','PP':25,'basepower':70,'accuracy':95,'description':'JUMP_KICK_EFFECT'},
    '27':{'name':"ROLLING KICK",'type':'FIGHTING','PP':15,'basepower':60,'accuracy':85,'description':'FLINCH_SIDE_EFFECT2'},
    '28':{'name':"SAND-ATTACK",'type':'GROUND','PP':15,'basepower':0,'accuracy':100,'description':'ACCURACY_DOWN1_EFFECT'},
    '29':{'name':"HEADBUTT",'type':'NORMAL','PP':15,'basepower':70,'accuracy':100,'description':'FLINCH_SIDE_EFFECT2'},
    '30':{'name':"HORN ATTACK",'type':'NORMAL','PP':25,'basepower':65,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '31':{'name':"FURY ATTACK",'type':'NORMAL','PP':20,'basepower':15,'accuracy':100,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '32':{'name':"HORN DRILL",'type':'NORMAL','PP':5,'basepower':1,'accuracy':50,'description':'OHKO_EFFECT'},
    '33':{'name':"TACKLE",'type':'NORMAL','PP':35,'basepower':35,'accuracy':95,'description':'NO_ADDITIONAL_EFFECT'},
    '34':{'name':"BODY SLAM",'type':'NORMAL','PP':15,'basepower':85,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT2'},
    '35':{'name':"WRAP",'type':'NORMAL','PP':20,'basepower':15,'accuracy':85,'description':'TRAPPING_EFFECT'},
    '36':{'name':"TAKE DOWN",'type':'NORMAL','PP':20,'basepower':90,'accuracy':85,'description':'RECOIL_EFFECT'},
    '37':{'name':"THRASH",'type':'NORMAL','PP':20,'basepower':90,'accuracy':100,'description':'THRASH_PETAL_DANCE_EFFECT'},
    '38':{'name':"DOUBLE-EDGE",'type':'NORMAL','PP':15,'basepower':100,'accuracy':100,'description':'RECOIL_EFFECT'},
    '39':{'name':"TAIL WHIP",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'DEFENSE_DOWN1_EFFECT'},
    '40':{'name':"POISON STING",'type':'POISON','PP':35,'basepower':15,'accuracy':100,'description':'POISON_SIDE_EFFECT1'},
    '41':{'name':"TWINEEDLE",'type':'BUG','PP':20,'basepower':40,'accuracy':100,'description':'TWINEEDLE_EFFECT'},
    '42':{'name':"PIN MISSILE",'type':'BUG','PP':20,'basepower':25,'accuracy':85,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '43':{'name':"LEER",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'DEFENSE_DOWN1_EFFECT'},
    '44':{'name':"BITE",'type':'NORMAL','PP':25,'basepower':60,'accuracy':100,'description':'FLINCH_SIDE_EFFECT1'},
    '45':{'name':"GROWL",'type':'NORMAL','PP':40,'basepower':0,'accuracy':100,'description':'ATTACK_DOWN1_EFFECT'},
    '46':{'name':"ROAR",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'SWITCH_AND_TELEPORT_EFFECT'},
    '47':{'name':"SING",'type':'NORMAL','PP':15,'basepower':0,'accuracy':70,'description':'SLEEP_EFFECT'},
    '48':{'name':"SUPERSONIC",'type':'NORMAL','PP':20,'basepower':0,'accuracy':70,'description':'CONFUSION_EFFECT'},
    '49':{'name':"SONICBOOM",'type':'NORMAL','PP':20,'basepower':40,'accuracy':90,'description':'SPECIAL_DAMAGE_EFFECT'},
    '50':{'name':"DISABLE",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'DISABLE_EFFECT'},
    '51':{'name':"ACID",'type':'POISON','PP':30,'basepower':40,'accuracy':100,'description':'DEFENSE_DOWN_SIDE_EFFECT'},
    '52':{'name':"EMBER",'type':'FIRE','PP':25,'basepower':40,'accuracy':100,'description':'BURN_SIDE_EFFECT1'},
    '53':{'name':"FLAMETHROWER",'type':'FIRE','PP':15,'basepower':95,'accuracy':100,'description':'BURN_SIDE_EFFECT1'},
    '54':{'name':"MIST",'type':'ICE','PP':30,'basepower':0,'accuracy':100,'description':'MIST_EFFECT'},
    '55':{'name':"WATER GUN",'type':'WATER','PP':20,'basepower':60,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '56':{'name':"HYDRO PUMP",'type':'WATER','PP':10,'basepower':100,'accuracy':90,'description':'NO_ADDITIONAL_EFFECT'},
    '57':{'name':"SURF",'type':'WATER','PP':15,'basepower':95,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '58':{'name':"ICE BEAM",'type':'ICE','PP':10,'basepower':95,'accuracy':100,'description':'FREEZE_SIDE_EFFECT'},
    '59':{'name':"BLIZZARD",'type':'ICE','PP':5,'basepower':120,'accuracy':90,'description':'FREEZE_SIDE_EFFECT'},
    '60':{'name':"PSYBEAM",'type':'PSYCHIC_TYPE','PP':20,'basepower':65,'accuracy':100,'description':'CONFUSION_SIDE_EFFECT'},
    '61':{'name':"BUBBLEBEAM",'type':'WATER','PP':20,'basepower':65,'accuracy':100,'description':'SPEED_DOWN_SIDE_EFFECT'},
    '62':{'name':"AURORA BEAM",'type':'ICE','PP':20,'basepower':65,'accuracy':100,'description':'ATTACK_DOWN_SIDE_EFFECT'},
    '63':{'name':"HYPER BEAM",'type':'NORMAL','PP':5,'basepower':150,'accuracy':90,'description':'HYPER_BEAM_EFFECT'},
    '64':{'name':"PECK",'type':'FLYING','PP':35,'basepower':35,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '65':{'name':"DRILL PECK",'type':'FLYING','PP':20,'basepower':80,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '66':{'name':"SUBMISSION",'type':'FIGHTING','PP':25,'basepower':80,'accuracy':100,'description':'RECOIL_EFFECT'},
    '67':{'name':"LOW KICK",'type':'FIGHTING','PP':20,'basepower':50,'accuracy':90,'description':'FLINCH_SIDE_EFFECT2'},
    '68':{'name':"COUNTER",'type':'FIGHTING','PP':20,'basepower':1,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '69':{'name':"SEISMIC TOSS",'type':'FIGHTING','PP':20,'basepower':0,'accuracy':100,'description':'SPECIAL_DAMAGE_EFFECT'},
    '70':{'name':"STRENGTH",'type':'NORMAL','PP':15,'basepower':80,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '71':{'name':"ABSORB",'type':'GRASS','PP':20,'basepower':40,'accuracy':100,'description':'DRAIN_HP_EFFECT'},
    '72':{'name':"MEGA DRAIN",'type':'GRASS','PP':10,'basepower':80,'accuracy':100,'description':'DRAIN_HP_EFFECT'},
    '73':{'name':"LEECH SEED",'type':'GRASS','PP':10,'basepower':0,'accuracy':90,'description':'LEECH_SEED_EFFECT'},
    '74':{'name':"GROWTH",'type':'NORMAL','PP':40,'basepower':0,'accuracy':100,'description':'SPECIAL_UP1_EFFECT'},
    '75':{'name':"RAZOR LEAF",'type':'GRASS','PP':25,'basepower':55,'accuracy':95,'description':'NO_ADDITIONAL_EFFECT'},
    '76':{'name':"SOLARBEAM",'type':'GRASS','PP':10,'basepower':120,'accuracy':100,'description':'CHARGE_EFFECT'},
    '77':{'name':"POISONPOWDER",'type':'POISON','PP':35,'basepower':0,'accuracy':75,'description':'POISON_EFFECT'},
    '78':{'name':"STUN SPORE",'type':'GRASS','PP':30,'basepower':0,'accuracy':75,'description':'PARALYZE_EFFECT'},
    '79':{'name':"SLEEP POWDER",'type':'GRASS','PP':15,'basepower':0,'accuracy':75,'description':'SLEEP_EFFECT'},
    '80':{'name':"PETAL DANCE",'type':'GRASS','PP':20,'basepower':85,'accuracy':100,'description':'THRASH_PETAL_DANCE_EFFECT'},
    '81':{'name':"STRING SHOT",'type':'BUG','PP':40,'basepower':0,'accuracy':95,'description':'SPEED_DOWN1_EFFECT'},
    '82':{'name':"DRAGON RAGE",'type':'DRAGON','PP':10,'basepower':70,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '83':{'name':"FIRE SPIN",'type':'FIRE','PP':15,'basepower':15,'accuracy':85,'description':'TRAPPING_EFFECT'},
    '84':{'name':"THUNDERSHOCK",'type':'ELECTRIC','PP':30,'basepower':40,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT1'},
    '85':{'name':"THUNDERBOLT",'type':'ELECTRIC','PP':15,'basepower':95,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT1'},
    '86':{'name':"THUNDER WAVE",'type':'ELECTRIC','PP':20,'basepower':0,'accuracy':100,'description':'PARALYZE_EFFECT'},
    '87':{'name':"THUNDER",'type':'ELECTRIC','PP':10,'basepower':120,'accuracy':70,'description':'PARALYZE_SIDE_EFFECT1'},
    '88':{'name':"ROCK THROW",'type':'ROCK','PP':15,'basepower':50,'accuracy':80,'description':'NO_ADDITIONAL_EFFECT'},
    '89':{'name':"EARTHQUAKE",'type':'GROUND','PP':10,'basepower':100,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '90':{'name':"FISSURE",'type':'GROUND','PP':5,'basepower':1,'accuracy':50,'description':'OHKO_EFFECT'},
    '91':{'name':"DIG",'type':'GROUND','PP':10,'basepower':60,'accuracy':100,'description':'CHARGE_EFFECT'},
    '92':{'name':"TOXIC",'type':'POISON','PP':10,'basepower':0,'accuracy':85,'description':'POISON_EFFECT'},
    '93':{'name':"CONFUSION",'type':'PSYCHIC_TYPE','PP':25,'basepower':50,'accuracy':100,'description':'CONFUSION_SIDE_EFFECT'},
    '94':{'name':"PSYCHIC",'type':'PSYCHIC_TYPE','PP':10,'basepower':90,'accuracy':100,'description':'SPECIAL_DOWN_SIDE_EFFECT'},
    '95':{'name':"HYPNOSIS",'type':'PSYCHIC_TYPE','PP':20,'basepower':0,'accuracy':60,'description':'SLEEP_EFFECT'},
    '96':{'name':"MEDITATE",'type':'PSYCHIC_TYPE','PP':40,'basepower':0,'accuracy':100,'description':'ATTACK_SPECIAL_SPEED_UP1'},
    '97':{'name':"AGILITY",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'SPEED_UP2_EFFECT'},
    '98':{'name':"QUICK ATTACK",'type':'NORMAL','PP':30,'basepower':40,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '99':{'name':"RAGE",'type':'NORMAL','PP':20,'basepower':40,'accuracy':100,'description':'RAGE_EFFECT'},
    '100':{'name':"TELEPORT",'type':'PSYCHIC_TYPE','PP':20,'basepower':0,'accuracy':100,'description':'SWITCH_AND_TELEPORT_EFFECT'},
    '101':{'name':"NIGHT SHADE",'type':'GHOST','PP':15,'basepower':0,'accuracy':100,'description':'SPECIAL_DAMAGE_EFFECT'},
    '102':{'name':"MIMIC",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'MIMIC_EFFECT'},
    '103':{'name':"SCREECH",'type':'NORMAL','PP':40,'basepower':0,'accuracy':85,'description':'DEFENSE_DOWN2_EFFECT'},
    '104':{'name':"DOUBLE TEAM",'type':'NORMAL','PP':15,'basepower':0,'accuracy':100,'description':'EVASION_UP1_EFFECT'},
    '105':{'name':"RECOVER",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'HEAL_EFFECT'},
    '106':{'name':"HARDEN",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'DEFENSE_UP1_EFFECT'},
    '107':{'name':"MINIMIZE",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'EVASION_UP1_EFFECT'},
    '108':{'name':"SMOKESCREEN",'type':'POISON','PP':20,'basepower':0,'accuracy':100,'description':'ACCURACY_DOWN1_EFFECT'},
    '109':{'name':"CONFUSE RAY",'type':'GHOST','PP':10,'basepower':0,'accuracy':100,'description':'CONFUSION_EFFECT'},
    '110':{'name':"WITHDRAW",'type':'WATER','PP':20,'basepower':0,'accuracy':100,'description':'HEAL_EFFECT'},
    '111':{'name':"DEFENSE CURL",'type':'NORMAL','PP':40,'basepower':0,'accuracy':100,'description':'DEFENSE_UP1_EFFECT'},
    '112':{'name':"BARRIER",'type':'PSYCHIC_TYPE','PP':30,'basepower':0,'accuracy':100,'description':'DEFENSE_UP2_EFFECT'},
    '113':{'name':"LIGHT SCREEN",'type':'PSYCHIC_TYPE','PP':30,'basepower':0,'accuracy':100,'description':'LIGHT_SCREEN_EFFECT'},
    '114':{'name':"HAZE",'type':'POISON','PP':30,'basepower':0,'accuracy':100,'description':'HAZE_EFFECT'},
    '115':{'name':"REFLECT",'type':'PSYCHIC_TYPE','PP':20,'basepower':0,'accuracy':100,'description':'REFLECT_EFFECT'},
    '116':{'name':"FOCUS ENERGY",'type':'GHOST','PP':20,'basepower':80,'accuracy':100,'description':'DEFENSE_DOWN_SIDE_EFFECT'},
    '117':{'name':"BIDE",'type':'ROCK','PP':15,'basepower':65,'accuracy':100,'description':'ATTACK_UP_SIDE_EFFECT'},
    '118':{'name':"METRONOME",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'METRONOME_EFFECT'},
    '119':{'name':"MIRROR MOVE",'type':'FLYING','PP':20,'basepower':0,'accuracy':100,'description':'MIRROR_MOVE_EFFECT'},
    '120':{'name':"SELFDESTRUCT",'type':'NORMAL','PP':5,'basepower':130,'accuracy':100,'description':'EXPLODE_EFFECT'},
    '121':{'name':"EGG BOMB",'type':'NORMAL','PP':10,'basepower':100,'accuracy':75,'description':'CONFUSION_SIDE_EFFECT'},
    '122':{'name':"LICK",'type':'GHOST','PP':30,'basepower':50,'accuracy':100,'description':'PARALYZE_SIDE_EFFECT2'},
    '123':{'name':"SMOG",'type':'POISON','PP':20,'basepower':40,'accuracy':90,'description':'POISON_SIDE_EFFECT2'},
    '124':{'name':"SLUDGE",'type':'POISON','PP':20,'basepower':65,'accuracy':100,'description':'POISON_SIDE_EFFECT2'},
    '125':{'name':"BONE CLUB",'type':'GROUND','PP':20,'basepower':65,'accuracy':85,'description':'FLINCH_SIDE_EFFECT1'},
    '126':{'name':"FIRE BLAST",'type':'FIRE','PP':5,'basepower':120,'accuracy':85,'description':'BURN_SIDE_EFFECT2'},
    '127':{'name':"WATERFALL",'type':'WATER','PP':15,'basepower':80,'accuracy':100,'description':'FLINCH_SIDE_EFFECT1'},
    '128':{'name':"CLAMP",'type':'WATER','PP':10,'basepower':35,'accuracy':90,'description':'TRAPPING_EFFECT'},
    '129':{'name':"SWIFT",'type':'NORMAL','PP':20,'basepower':65,'accuracy':100,'description':'SWIFT_EFFECT'},
    '130':{'name':"SKULL BASH",'type':'NORMAL','PP':15,'basepower':100,'accuracy':100,'description':'RECOIL_EFFECT'},
    '131':{'name':"SPIKE CANNON",'type':'NORMAL','PP':15,'basepower':20,'accuracy':100,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '132':{'name':"CONSTRICT",'type':'NORMAL','PP':35,'basepower':40,'accuracy':100,'description':'SPEED_DOWN_SIDE_EFFECT'},
    '133':{'name':"AMNESIA",'type':'PSYCHIC_TYPE','PP':20,'basepower':0,'accuracy':100,'description':'SPECIAL_UP2_EFFECT'},
    '134':{'name':"KINESIS",'type':'PSYCHIC_TYPE','PP':15,'basepower':0,'accuracy':100,'description':'ACCURACY_DOWN1_EFFECT'},
    '135':{'name':"SOFTBOILED",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'HEAL_EFFECT'},
    '136':{'name':"HI JUMP KICK",'type':'FIGHTING','PP':20,'basepower':85,'accuracy':90,'description':'JUMP_KICK_EFFECT'},
    '137':{'name':"GLARE",'type':'NORMAL','PP':30,'basepower':0,'accuracy':90,'description':'PARALYZE_EFFECT'},
    '138':{'name':"DREAM EATER",'type':'GHOST','PP':15,'basepower':100,'accuracy':100,'description':'DREAM_EATER_EFFECT'},
    '139':{'name':"POISON GAS",'type':'POISON','PP':40,'basepower':0,'accuracy':100,'description':'POISON_EFFECT'},
    '140':{'name':"BARRAGE",'type':'GRASS','PP':20,'basepower':15,'accuracy':100,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '141':{'name':"LEECH LIFE",'type':'BUG','PP':15,'basepower':50,'accuracy':100,'description':'DRAIN_HP_EFFECT'},
    '142':{'name':"LOVELY KISS",'type':'NORMAL','PP':10,'basepower':0,'accuracy':80,'description':'SLEEP_EFFECT'},
    '143':{'name':"SKY ATTACK",'type':'FLYING','PP':5,'basepower':140,'accuracy':90,'description':'HYPER_BEAM_EFFECT'},
    '144':{'name':"TRANSFORM",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'TRANSFORM_EFFECT'},
    '145':{'name':"BUBBLE",'type':'WATER','PP':30,'basepower':20,'accuracy':100,'description':'SPEED_DOWN_SIDE_EFFECT'},
    '146':{'name':"DIZZY PUNCH",'type':'NORMAL','PP':10,'basepower':70,'accuracy':100,'description':'CONFUSION_SIDE_EFFECT'},
    '147':{'name':"SPORE",'type':'GRASS','PP':15,'basepower':0,'accuracy':100,'description':'SLEEP_EFFECT'},
    '148':{'name':"FLASH",'type':'NORMAL','PP':20,'basepower':0,'accuracy':100,'description':'ACCURACY_DOWN1_EFFECT'},
    '149':{'name':"PSYWAVE",'type':'PSYCHIC_TYPE','PP':15,'basepower':1,'accuracy':80,'description':'SPECIAL_DAMAGE_EFFECT'},
    '150':{'name':"SPLASH",'type':'NORMAL','PP':40,'basepower':0,'accuracy':100,'description':'SPLASH_EFFECT'},
    '151':{'name':"ACID ARMOR",'type':'POISON','PP':40,'basepower':0,'accuracy':100,'description':'DEFENSE_UP2_EFFECT'},
    '152':{'name':"CRABHAMMER",'type':'WATER','PP':10,'basepower':90,'accuracy':85,'description':'NO_ADDITIONAL_EFFECT'},
    '153':{'name':"EXPLOSION",'type':'NORMAL','PP':5,'basepower':170,'accuracy':100,'description':'EXPLODE_EFFECT'},
    '154':{'name':"FURY SWIPES",'type':'NORMAL','PP':15,'basepower':25,'accuracy':80,'description':'TWO_TO_FIVE_ATTACKS_EFFECT'},
    '155':{'name':"BONEMERANG",'type':'GROUND','PP':10,'basepower':50,'accuracy':90,'description':'ATTACK_TWICE_EFFECT'},
    '156':{'name':"REST",'type':'PSYCHIC_TYPE','PP':10,'basepower':0,'accuracy':100,'description':'HEAL_EFFECT'},
    '157':{'name':"ROCK SLIDE",'type':'ROCK','PP':15,'basepower':75,'accuracy':90,'description':'FLINCH_SIDE_EFFECT1'},
    '158':{'name':"HYPER FANG",'type':'NORMAL','PP':15,'basepower':80,'accuracy':90,'description':'FLINCH_SIDE_EFFECT1'},
    '159':{'name':"SHARPEN",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'ATTACK_ACCURACY_UP1_EFFECT'},
    '160':{'name':"CONVERSION",'type':'NORMAL','PP':30,'basepower':0,'accuracy':100,'description':'CONVERSION_EFFECT'},
    '161':{'name':"TRI ATTACK",'type':'NORMAL','PP':10,'basepower':80,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '162':{'name':"SUPER FANG",'type':'NORMAL','PP':10,'basepower':1,'accuracy':90,'description':'SUPER_FANG_EFFECT'},
    '163':{'name':"SLASH",'type':'NORMAL','PP':20,'basepower':70,'accuracy':100,'description':'NO_ADDITIONAL_EFFECT'},
    '164':{'name':"SUBSTITUTE",'type':'NORMAL','PP':10,'basepower':0,'accuracy':100,'description':'SUBSTITUTE_EFFECT'},
    '165':{'name':"STRUGGLE",'type':'TYPELESS','PP':10,'basepower':50,'accuracy':100,'description':'RECOIL_EFFECT'}
};

const statusDict = {
    '0':'HEALTHY',
    '3':'ASLEEP',
    '4':'POISON',
    '5':'BURNED',
    '6':'FROZEN',
    '7':'PARALYZED'
};

const typeDict = {
    '0':'NORMAL',
    '1':'FIGHTING',
    '2':'FLYING',
    '3':'POISON',
    '4':'GROUND',
    '5':'ROCK',
    '7':'BUG',
    '8':'GHOST',
    '20':'FIRE',
    '21':'WATER',
    '22':'GRASS',
    '23':'ELECTRIC',
    '24':'PSYCHIC',
    '25':'ICE',
    '26':'DRAGON'
};

const dexDict = {
    '1': {'name':'rhydon', 'pokedexNo':'112'},
    '2': {'name':'kangaskhan', 'pokedexNo':'115'},
    '3': {'name':'nidoran_m', 'pokedexNo':'032'},
    '4': {'name':'clefairy', 'pokedexNo':'035'},
    '5': {'name':'spearow', 'pokedexNo':'021'},
    '6': {'name':'voltorb', 'pokedexNo':'100'},
    '7': {'name':'nidoking', 'pokedexNo':'035'},
    '8': {'name':'slowbro', 'pokedexNo':'080'},
    '9': {'name':'ivysaur', 'pokedexNo':'002'},
    '10': {'name':'exeggutor', 'pokedexNo':'103'},
    '11': {'name':'lickitung', 'pokedexNo':'108'},
    '12': {'name':'exeggcute', 'pokedexNo':'102'},
    '13': {'name':'grimer', 'pokedexNo':'088'},
    '14': {'name':'gengar', 'pokedexNo':'094'},
    '15': {'name':'nidoran_f', 'pokedexNo':'029'},
    '16': {'name':'nidoqueen', 'pokedexNo':'031'},
    '17': {'name':'cubone', 'pokedexNo':'104'},
    '18': {'name':'rhyhorn', 'pokedexNo':'111'},
    '19': {'name':'lapras', 'pokedexNo':'131'},
    '20': {'name':'arcanine', 'pokedexNo':'059'},
    '21': {'name':'mew', 'pokedexNo':'151'},
    '22': {'name':'gyarados', 'pokedexNo':'130'},
    '23': {'name':'shellder', 'pokedexNo':'090'},
    '24': {'name':'tentacool', 'pokedexNo':'072'},
    '25': {'name':'gastly', 'pokedexNo':'092'},
    '26': {'name':'scyther', 'pokedexNo':'123'},
    '27': {'name':'staryu', 'pokedexNo':'120'},
    '28': {'name':'blastoise', 'pokedexNo':'009'},
    '29': {'name':'pinsir', 'pokedexNo':'127'},
    '30': {'name':'tangela', 'pokedexNo':'114'},
    '31': {'name':'missingno', 'pokedexNo':'NULL'},
    '32': {'name':'missingno', 'pokedexNo':'NULL'},
    '33': {'name':'growlithe', 'pokedexNo':'058'},
    '34': {'name':'onix', 'pokedexNo':'095'},
    '35': {'name':'fearow', 'pokedexNo':'022'},
    '36': {'name':'pidgey', 'pokedexNo':'016'},
    '37': {'name':'slowpoke', 'pokedexNo':'079'},
    '38': {'name':'kadabra', 'pokedexNo':'064'},
    '39': {'name':'graveler', 'pokedexNo':'075'},
    '40': {'name':'chansey', 'pokedexNo':'113'},
    '41': {'name':'machoke', 'pokedexNo':'067'},
    '42': {'name':'mr.mime', 'pokedexNo':'122'},
    '43': {'name':'hitmonlee', 'pokedexNo':'106'},
    '44': {'name':'hitmonchan', 'pokedexNo':'107'},
    '45': {'name':'arbok', 'pokedexNo':'024'},
    '46': {'name':'parasect', 'pokedexNo':'047'},
    '47': {'name':'psyduck', 'pokedexNo':'054'},
    '48': {'name':'drowzee', 'pokedexNo':'096'},
    '49': {'name':'golem', 'pokedexNo':'076'},
    '50': {'name':'missingno', 'pokedexNo':'NULL'},
    '51': {'name':'magmar', 'pokedexNo':'126'},
    '52': {'name':'missingno', 'pokedexNo':'NULL'},
    '53': {'name':'electabuzz', 'pokedexNo':'125'},
    '54': {'name':'magneton', 'pokedexNo':'082'},
    '55': {'name':'koffing', 'pokedexNo':'109'},
    '56': {'name':'missingno', 'pokedexNo':'NULL'},
    '57': {'name':'mankey', 'pokedexNo':'056'},
    '58': {'name':'seel', 'pokedexNo':'086'},
    '59': {'name':'diglett', 'pokedexNo':'050'},
    '60': {'name':'tauros', 'pokedexNo':'128'},
    '61': {'name':'missingno', 'pokedexNo':'NULL'},
    '62': {'name':'missingno', 'pokedexNo':'NULL'},
    '63': {'name':'missingno', 'pokedexNo':'NULL'},
    '64': {'name':'farfetchd', 'pokedexNo':'083'},
    '65': {'name':'venonat', 'pokedexNo':'048'},
    '66': {'name':'dragonite', 'pokedexNo':'149'},
    '67': {'name':'missingno', 'pokedexNo':'NULL'},
    '68': {'name':'missingno', 'pokedexNo':'NULL'},
    '69': {'name':'missingno', 'pokedexNo':'NULL'},
    '70': {'name':'doduo', 'pokedexNo':'084'},
    '71': {'name':'poliwag', 'pokedexNo':'060'},
    '72': {'name':'jynx', 'pokedexNo':'124'},
    '73': {'name':'moltres', 'pokedexNo':'146'},
    '74': {'name':'articuno', 'pokedexNo':'144'},
    '75': {'name':'zapdos', 'pokedexNo':'145'},
    '76': {'name':'ditto', 'pokedexNo':'132'},
    '77': {'name':'meowth', 'pokedexNo':'052'},
    '78': {'name':'krabby', 'pokedexNo':'098'},
    '79': {'name':'missingno', 'pokedexNo':'NULL'},
    '80': {'name':'missingno', 'pokedexNo':'NULL'},
    '81': {'name':'missingno', 'pokedexNo':'NULL'},
    '82': {'name':'vulpix', 'pokedexNo':'037'},
    '83': {'name':'ninetales', 'pokedexNo':'038'},
    '84': {'name':'pikachu', 'pokedexNo':'025'},
    '85': {'name':'raichu', 'pokedexNo':'026'},
    '86': {'name':'missingno', 'pokedexNo':'NULL'},
    '87': {'name':'missingno', 'pokedexNo':'NULL'},
    '88': {'name':'dratini', 'pokedexNo':'147'},
    '89': {'name':'dragonair', 'pokedexNo':'148'},
    '90': {'name':'kabuto', 'pokedexNo':'140'},
    '91': {'name':'kabutops', 'pokedexNo':'141'},
    '92': {'name':'horsea', 'pokedexNo':'116'},
    '93': {'name':'seadra', 'pokedexNo':'117'},
    '94': {'name':'missingno', 'pokedexNo':'NULL'},
    '95': {'name':'missingno', 'pokedexNo':'NULL'},
    '96': {'name':'sandshrew', 'pokedexNo':'027'},
    '97': {'name':'sandslash', 'pokedexNo':'028'},
    '98': {'name':'omanyte', 'pokedexNo':'138'},
    '99': {'name':'omastar', 'pokedexNo':'139'},
    '100': {'name':'jigglypuff', 'pokedexNo':'039'},
    '101': {'name':'wigglytuff', 'pokedexNo':'040'},
    '102': {'name':'eevee', 'pokedexNo':'133'},
    '103': {'name':'flareon', 'pokedexNo':'136'},
    '104': {'name':'jolteon', 'pokedexNo':'135'},
    '105': {'name':'vaporeon', 'pokedexNo':'134'},
    '106': {'name':'machop', 'pokedexNo':'066'},
    '107': {'name':'zubat', 'pokedexNo':'041'},
    '108': {'name':'ekans', 'pokedexNo':'023'},
    '109': {'name':'paras', 'pokedexNo':'046'},
    '110': {'name':'poliwhirl', 'pokedexNo':'061'},
    '111': {'name':'poliwrath', 'pokedexNo':'062'},
    '112': {'name':'weedle', 'pokedexNo':'013'},
    '113': {'name':'kakuna', 'pokedexNo':'014'},
    '114': {'name':'beedrill', 'pokedexNo':'015'},
    '115': {'name':'missingno', 'pokedexNo':'NULL'},
    '116': {'name':'dodrio', 'pokedexNo':'085'},
    '117': {'name':'primeape', 'pokedexNo':'057'},
    '118': {'name':'dugtrio', 'pokedexNo':'051'},
    '119': {'name':'venomoth', 'pokedexNo':'049'},
    '120': {'name':'dewgong', 'pokedexNo':'087'},
    '121': {'name':'missingno', 'pokedexNo':'NULL'},
    '122': {'name':'missingno', 'pokedexNo':'NULL'},
    '123': {'name':'caterpie', 'pokedexNo':'010'},
    '124': {'name':'metapod', 'pokedexNo':'011'},
    '125': {'name':'butterfree', 'pokedexNo':'012'},
    '126': {'name':'machamp', 'pokedexNo':'068'},
    '127': {'name':'missingno', 'pokedexNo':'NULL'},
    '128': {'name':'golduck', 'pokedexNo':'055'},
    '129': {'name':'hypno', 'pokedexNo':'097'},
    '130': {'name':'golbat', 'pokedexNo':'042'},
    '131': {'name':'mewtwo', 'pokedexNo':'150'},
    '132': {'name':'snorlax', 'pokedexNo':'143'},
    '133': {'name':'magikarp', 'pokedexNo':'129'},
    '134': {'name':'missingno', 'pokedexNo':'NULL'},
    '135': {'name':'missingno', 'pokedexNo':'NULL'},
    '136': {'name':'muk', 'pokedexNo':'089'},
    '137': {'name':'missingno', 'pokedexNo':'NULL'},
    '138': {'name':'kingler', 'pokedexNo':'099'},
    '139': {'name':'cloyster', 'pokedexNo':'091'},
    '140': {'name':'missingno', 'pokedexNo':'NULL'},
    '141': {'name':'electrode', 'pokedexNo':'101'},
    '142': {'name':'clefable', 'pokedexNo':'036'},
    '143': {'name':'weezing', 'pokedexNo':'110'},
    '144': {'name':'persian', 'pokedexNo':'053'},
    '145': {'name':'marowak', 'pokedexNo':'105'},
    '146': {'name':'missingno', 'pokedexNo':'NULL'},
    '147': {'name':'haunter', 'pokedexNo':'093'},
    '148': {'name':'abra', 'pokedexNo':'063'},
    '149': {'name':'alakazam', 'pokedexNo':'065'},
    '150': {'name':'pidgeotto', 'pokedexNo':'017'},
    '151': {'name':'pidgeot', 'pokedexNo':'018'},
    '152': {'name':'starmie', 'pokedexNo':'121'},
    '153': {'name':'bulbasaur', 'pokedexNo':'001'},
    '154': {'name':'venusaur', 'pokedexNo':'003'},
    '155': {'name':'tentacruel', 'pokedexNo':'073'},
    '156': {'name':'missingno', 'pokedexNo':'NULL'},
    '157': {'name':'goldeen', 'pokedexNo':'118'},
    '158': {'name':'seaking', 'pokedexNo':'119'},
    '159': {'name':'missingno', 'pokedexNo':'NULL'},
    '160': {'name':'missingno', 'pokedexNo':'NULL'},
    '161': {'name':'missingno', 'pokedexNo':'NULL'},
    '162': {'name':'missingno', 'pokedexNo':'NULL'},
    '163': {'name':'ponyta', 'pokedexNo':'077'},
    '164': {'name':'rapidash', 'pokedexNo':'078'},
    '165': {'name':'rattata', 'pokedexNo':'019'},
    '166': {'name':'raticate', 'pokedexNo':'020'},
    '167': {'name':'nidorino', 'pokedexNo':'033'},
    '168': {'name':'nidorina', 'pokedexNo':'030'},
    '169': {'name':'geodude', 'pokedexNo':'074'},
    '170': {'name':'porygon', 'pokedexNo':'137'},
    '171': {'name':'aerodactyl', 'pokedexNo':'142'},
    '172': {'name':'missingno', 'pokedexNo':'NULL'},
    '173': {'name':'magnemite', 'pokedexNo':'081'},
    '174': {'name':'missingno', 'pokedexNo':'NULL'},
    '175': {'name':'missingno', 'pokedexNo':'NULL'},
    '176': {'name':'charmander', 'pokedexNo':'004'},
    '177': {'name':'squirtle', 'pokedexNo':'007'},
    '178': {'name':'charmeleon', 'pokedexNo':'005'},
    '179': {'name':'wartortle', 'pokedexNo':'008'},
    '180': {'name':'charizard', 'pokedexNo':'006'},
    '181': {'name':'missingno', 'pokedexNo':'NULL'},
    '182': {'name':'missingno', 'pokedexNo':'NULL'},
    '183': {'name':'missingno', 'pokedexNo':'NULL'},
    '184': {'name':'missingno', 'pokedexNo':'NULL'},
    '185': {'name':'oddish', 'pokedexNo':'043'},
    '186': {'name':'gloom', 'pokedexNo':'044'},
    '187': {'name':'vileplume', 'pokedexNo':'045'},
    '188': {'name':'bellsprout', 'pokedexNo':'069'},
    '189': {'name':'weepinbell', 'pokedexNo':'070'},
    '190': {'name':'victreebel', 'pokedexNo':'071'},
};