# Generated by Django 3.2.7 on 2021-12-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0014_rename_user_id_credentials_profile_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credentials_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='credentials_profile',
            field=models.ManyToManyField(to='marvel.Credential'),
        ),
    ]
