# Generated by Django 3.2.7 on 2021-12-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211219_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='credentials_profile',
            new_name='credentials',
        ),
    ]
