# Generated by Django 3.2.7 on 2021-09-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_text', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_text', models.CharField(max_length=64)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, max_length=64, null=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marvel.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('platform', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marvel.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('alias_text', models.CharField(max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('movie', models.ManyToManyField(to='marvel.Movie')),
            ],
        ),
    ]
