# Generated by Django 3.2.7 on 2021-09-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_text', models.CharField(max_length=64)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, max_length=64, null=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marvel.platform')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='series',
            field=models.ManyToManyField(to='marvel.Series'),
        ),
    ]
