# Generated by Django 3.2.7 on 2021-10-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
