# Generated by Django 3.2.7 on 2021-11-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0003_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenwriter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
