# Generated by Django 3.2.7 on 2021-11-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0004_auto_20211126_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='screenwriter',
            new_name='screenwriters',
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
