# Generated by Django 3.2.7 on 2021-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0006_auto_20211126_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='details',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
