# Generated by Django 3.2.7 on 2021-12-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0007_movie_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='details',
        ),
    ]
