# Generated by Django 3.2.7 on 2021-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0008_remove_movie_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
