# Generated by Django 3.2.7 on 2021-12-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0010_series_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
