# Generated by Django 3.2.7 on 2021-12-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0011_auto_20211211_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
