# Generated by Django 3.2.7 on 2021-12-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0013_credentials_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials_profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
