# Generated by Django 3.2.7 on 2021-12-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211219_1939'),
        ('marvel', '0014_rename_user_id_credentials_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials_Profile',
        ),
    ]
