# Generated by Django 3.2.7 on 2022-01-16 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prefix', models.CharField(blank=True, max_length=64, null=True)),
                ('name_base', models.CharField(max_length=64)),
                ('equipment', models.CharField(blank=True, max_length=64, null=True)),
                ('unilateral', models.BooleanField(blank=True, default=False)),
                ('modality', models.CharField(blank=True, max_length=64, null=True)),
                ('movement_type', models.CharField(blank=True, max_length=64, null=True)),
                ('goal_power', models.FloatField(blank=True, null=True)),
                ('goal_strength', models.FloatField(blank=True, null=True)),
                ('goal_stamina', models.FloatField(blank=True, null=True)),
                ('goal_endurance', models.FloatField(blank=True, null=True)),
                ('goal_speed', models.FloatField(blank=True, null=True)),
                ('corr_chest', models.FloatField(blank=True, default=0.0)),
                ('corr_shoulders', models.FloatField(blank=True, default=0.0)),
                ('corr_biceps', models.FloatField(blank=True, default=0.0)),
                ('corr_tricps', models.FloatField(blank=True, default=0.0)),
                ('corr_forearms', models.FloatField(blank=True, default=0.0)),
                ('corr_neck', models.FloatField(blank=True, default=0.0)),
                ('corr_abs', models.FloatField(blank=True, default=0.0)),
                ('corr_traps', models.FloatField(blank=True, default=0.0)),
                ('corr_rhomboids', models.FloatField(blank=True, default=0.0)),
                ('corr_lats', models.FloatField(blank=True, default=0.0)),
                ('corr_obliques', models.FloatField(blank=True, default=0.0)),
                ('corr_quads', models.FloatField(blank=True, default=0.0)),
                ('corr_hamstrings', models.FloatField(blank=True, default=0.0)),
                ('corr_glutes', models.FloatField(blank=True, default=0.0)),
                ('corr_calves', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('workout_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('measure_text', models.CharField(max_length=64)),
                ('measure', models.FloatField(blank=True, null=True)),
                ('measurement_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.measurementlog')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('power', models.FloatField(blank=True, null=True)),
                ('strength', models.FloatField(blank=True, null=True)),
                ('stamina', models.FloatField(blank=True, null=True)),
                ('endurance', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('fitness_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.fitnesslog')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_count', models.IntegerField(blank=True, null=True)),
                ('rep_count', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('tempo', models.CharField(blank=True, max_length=4, null=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.exercise')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.workout')),
            ],
        ),
    ]
