# Generated by Django 3.2.7 on 2022-01-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='corr_tricps',
            new_name='corr_triceps',
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_lower_back',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
