# Generated by Django 3.2.7 on 2021-12-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='base_name',
            new_name='name_base',
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_abs',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_biceps',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_calves',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_chest',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_glutes',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_hamstrings',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_lats',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_neck',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_obliques',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_quads',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_rhomboids',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_shoulders',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_traps',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_tricps',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_endurance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_stamina',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='modality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_prefix',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='unilateral',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
