# Generated by Django 3.2.7 on 2021-12-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20211219_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='corr_forearms',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField()),
                ('set_count', models.IntegerField(blank=True, null=True)),
                ('rep_count', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('exercise_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.exercise')),
            ],
        ),
    ]
