# Generated by Django 3.2.7 on 2021-12-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20211219_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=256)),
                ('food_group', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
