# Generated by Django 3.2.7 on 2021-12-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20211219_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitness',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='exercise_id',
            new_name='exercise',
        ),
    ]
