# Generated by Django 3.2.7 on 2022-01-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20220121_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='corr_abs',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_biceps',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_calves',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_chest',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_forearms',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_glutes',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_hamstrings',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_lats',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_lower_back',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_neck',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_obliques',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_quads',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_rhomboids',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_shoulders',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_traps',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_triceps',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_endurance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_stamina',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_strength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
