# Generated by Django 3.2.7 on 2022-01-21 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0007_auto_20220121_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='goal_endurance',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='goal_power',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='goal_speed',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='goal_stamina',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='goal_strength',
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_power', models.FloatField(blank=True, null=True)),
                ('goal_strength', models.FloatField(blank=True, null=True)),
                ('goal_stamina', models.FloatField(blank=True, null=True)),
                ('goal_endurance', models.FloatField(blank=True, null=True)),
                ('goal_speed', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.exercise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
