# Generated by Django 3.2.7 on 2022-01-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_alter_goal_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseentry',
            options={'verbose_name_plural': 'Exercise Entries'},
        ),
        migrations.AlterModelOptions(
            name='fitnessentry',
            options={'verbose_name_plural': 'Fitness Entries'},
        ),
        migrations.AlterModelOptions(
            name='measuremententry',
            options={'verbose_name_plural': 'Measurement Entries'},
        ),
        migrations.AddField(
            model_name='workout',
            name='load_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
