# Generated by Django 3.2.7 on 2022-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_auto_20220121_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnesslog',
            options={'verbose_name_plural': 'Fitness Log'},
        ),
        migrations.AlterModelOptions(
            name='measurementlog',
            options={'verbose_name_plural': 'Measurement Log'},
        ),
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'verbose_name_plural': 'Workout Log'},
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='superset',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
