# Generated by Django 3.2.7 on 2022-01-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_auto_20220123_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='load_volume',
            new_name='volume',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
    ]
