# Generated by Django 3.2.7 on 2022-01-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_auto_20220123_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='load_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
