# Generated by Django 3.2.7 on 2022-01-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_auto_20220123_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseentry',
            name='superset',
        ),
    ]
