# Generated by Django 3.2.7 on 2022-01-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_remove_exerciseentry_superset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='corr_endurance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_stamina',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='corr_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseentry',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout'),
        ),
    ]
