# Generated by Django 3.2.7 on 2022-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_auto_20220125_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='corr_endurance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='corr_power',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='corr_speed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='corr_stamina',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='corr_strength',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
