"use client"

import React, { Suspense } from "react";
import { Amplify } from "aws-amplify";
import "@/src/styles/app.css";
import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import outputs from "@/amplify_outputs.json";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";
import { Metadata } from "next";

Amplify.configure(outputs);

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Authenticator.Provider >
          <Suspense>
            <Navigation />
            {children}
            <Footer />
          </Suspense>
        </Authenticator.Provider >
      </body>
    </html>
  );
}

