# Generated by Django 3.2.7 on 2021-12-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
